#!/bin/bash
# fetch-resources.sh — re-fetch the re-downloadable resources that were removed
# from this slimmed delivery tree for the `trino-0` StarryOS case.
#
# WHAT THIS RESTORES (exact paths/names that prep-trino-rootfs.sh expects):
#   package/trino-server-476.tar.gz          (Trino 476 server dist, ~821 MB — reference only)
#   package/trino-cli-481-executable.jar     (Trino 481 self-executable CLI jar — reference only)
#   package/target/trino-libs/*.jar          (~193 trino-435 runtime deps; regenerated by maven)
#
# NOTE on what prep ACTUALLY consumes: prep-trino-rootfs.sh stages
# package/target/trino-demo.jar (kept in this tree) + package/target/trino-libs/*.jar
# + jna/* (kept). The server-476 tar and cli-481 jar are kept here only as the
# documented reference artifacts (SOURCES.md §2); they are NOT injected by prep.
#
# sha256 values are taken verbatim from ../../bigapps/SOURCES.md (authoritative).
# REQUIRES NETWORK. After running this, run prep-trino-rootfs.sh <arch>.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"

# fetch <url> <dest> <sha256>: skip if dest already matches; else download + verify.
fetch() {
  local url="$1" dest="$2" sha="$3" got
  if [ -f "$dest" ] && [ "$(sha256sum "$dest" | awk '{print $1}')" = "$sha" ]; then
    echo "  ok (cached): ${dest#$HERE/}"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  echo "  fetching: $url"
  if command -v curl >/dev/null 2>&1; then
    curl -fL --retry 3 -o "$dest" "$url"
  else
    wget -O "$dest" "$url"
  fi
  got="$(sha256sum "$dest" | awk '{print $1}')"
  if [ "$got" != "$sha" ]; then
    echo "  SHA256 MISMATCH for ${dest#$HERE/}" >&2
    echo "    expected $sha" >&2
    echo "    got      $got" >&2
    rm -f "$dest"
    exit 1
  fi
  echo "  verified: ${dest#$HERE/}"
}

echo "=== trino: reference upstream artifacts (Maven Central / GitHub release) ==="
# Trino server tarball — Maven Central (821 MB, the largest single file in the set).
fetch "https://repo1.maven.org/maven2/io/trino/trino-server/476/trino-server-476.tar.gz" \
      "$HERE/package/trino-server-476.tar.gz" \
      "cfd5accde17e8ebd251eeeb78aed1f490e77bb3a164d95a0f454bf8a7c1cbd3f"
# Trino CLI self-executable jar — Maven Central (classifier=executable).
# Identical artifact is also published at GitHub release:
#   https://github.com/trinodb/trino/releases/download/481/trino-cli-481
fetch "https://repo1.maven.org/maven2/io/trino/trino-cli/481/trino-cli-481-executable.jar" \
      "$HERE/package/trino-cli-481-executable.jar" \
      "9532fb7a47dc54eec4041e86d980991236c131fd6e34983e40f735ccf60bad7f"

echo "=== trino: runtime deps (package/target/trino-libs/) via maven ==="
# The ~193 trino-435 runtime jars are NOT a single downloadable artifact; they are
# resolved from Maven Central by the project POM. SOURCES.md documents the exact
# regeneration command. This needs a JDK + maven + network. trino-demo.jar (kept
# in this tree) is rebuilt as a harmless side effect.
LIBS="$HERE/package/target/trino-libs"
if [ -d "$LIBS" ] && [ "$(ls "$LIBS"/*.jar 2>/dev/null | wc -l)" -ge 190 ]; then
  echo "  ok (cached): package/target/trino-libs/ ($(ls "$LIBS"/*.jar | wc -l) jars)"
elif command -v mvn >/dev/null 2>&1; then
  echo "  running: mvn -f package/pom.xml package -DskipTests"
  mvn -f "$HERE/package/pom.xml" package -DskipTests
  echo "  generated: package/target/trino-libs/ ($(ls "$LIBS"/*.jar 2>/dev/null | wc -l) jars)"
else
  echo "  WARN: maven (mvn) not found — cannot regenerate package/target/trino-libs/." >&2
  echo "        Install a JDK + maven, then run (needs network):" >&2
  echo "          mvn -f \"$HERE/package/pom.xml\" package -DskipTests" >&2
  echo "        This resolves the ~193 trino-435 runtime deps into package/target/trino-libs/." >&2
  exit 1
fi

echo "fetch-resources: trino OK"
