#!/bin/bash
# fetch-resources.sh (hdl/bluesv/core)
# -----------------------------------------------------------------------------
# Purpose: re-acquire any re-downloadable resources removed during repo slimming
# so that prep-bluesv-rootfs.sh can build the rootfs. Run BEFORE prep-*.sh.
# Network is needed only for the OPTIONAL source rebuild (FETCH_SOURCES=1).
#
# STATUS for this app: NOTHING is required for prep. Every resource consumed by
# prep-bluesv-rootfs.sh is a self-built, hard-to-reproduce artifact kept in slim:
#   - testbin/vvp-<arch>      (STATIC Icarus vvp runtime, VCD + system VPI embedded;
#                              same runtime as ../../iverilog, kept)
#   - bluesv.vvp              (bsc -verilog -e mkTb -vsim iverilog output, then
#                              :vpi_module rewritten to "system"; kept)
#   - bluesv-golden.txt       (host golden; kept)
# The base rootfs-<arch>-alpine.img comes from the maintainer's TGOSKITS_ROOT
# checkout, NOT from this repo.
#
# OPTIONAL (FETCH_SOURCES=1): regenerate the inputs from source.
#   * bluesv.vvp is generated by the Bluespec compiler bsc 2026.01 from Tb.bsv
#     (host /usr/local/bsc, BLUESPECDIR=/usr/local/bsc/lib). bsc is a host-exclusive
#     toolchain (no fetchable repo artifact, no sha256 in SOURCES.md) — install it
#     from github.com/B-Lang-org/bsc and re-run bsc per SOURCES.md.
#   * The static vvp runtime is rebuilt from Icarus Verilog v12_0 source via
#     ../../iverilog/vvp-static-build/ (BUILD.md). The upstream source tarball is
#     fetched here (URL from SOURCES.md; no sha256 -> manual verify).
# -----------------------------------------------------------------------------
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"

# fetch <url> <dest> <sha256|->   ('-' = no authoritative sha256 in SOURCES.md)
fetch() {
    local url="$1" dest="$2" want="$3"
    mkdir -p "$(dirname "$dest")"
    if [ -f "$dest" ]; then
        if [ "$want" != "-" ] && echo "$want  $dest" | sha256sum -c - >/dev/null 2>&1; then
            echo "  [skip] ${dest##*/} (sha256 ok)"; return 0
        elif [ "$want" = "-" ]; then
            echo "  [have] ${dest##*/} (no authoritative sha256 in SOURCES.md; verify manually)"; return 0
        fi
    fi
    echo "  [get ] $url"
    if command -v curl >/dev/null 2>&1; then curl -fL --retry 3 -o "$dest" "$url"
    else wget -O "$dest" "$url"; fi
    if [ "$want" != "-" ]; then
        echo "$want  $dest" | sha256sum -c - >/dev/null 2>&1 || { echo "  sha256 MISMATCH: $dest" >&2; rm -f "$dest"; exit 1; }
        echo "  [ok  ] ${dest##*/} (sha256 verified)"
    else
        echo "  [warn] ${dest##*/} fetched; SOURCES.md has no sha256 — verify manually" >&2
    fi
}

echo "fetch-resources: bluesv/core — verifying retained self-built artifacts"
miss=0
for a in x86_64 aarch64 riscv64 loongarch64; do
    f="$HERE/testbin/vvp-$a"
    if [ -f "$f" ]; then echo "  [have] testbin/vvp-$a"; else echo "  [MISS] testbin/vvp-$a (rebuild via ../../iverilog/vvp-static-build)"; miss=1; fi
done
[ -f "$HERE/bluesv.vvp" ]        && echo "  [have] bluesv.vvp"        || { echo "  [MISS] bluesv.vvp (regen with bsc, FETCH_SOURCES=1)"; miss=1; }
[ -f "$HERE/bluesv-golden.txt" ] && echo "  [have] bluesv-golden.txt" || { echo "  [MISS] bluesv-golden.txt"; miss=1; }

if [ "${FETCH_SOURCES:-0}" = "1" ]; then
    echo "fetch-resources: bluesv/core — OPTIONAL: fetching Icarus Verilog v12_0 source (for the static vvp runtime)"
    fetch "https://codeload.github.com/steveicarus/iverilog/tar.gz/refs/tags/v12_0" \
          "$HERE/.srcbuild/iverilog-v12_0.tar.gz" "-"
    echo "  next: rebuild vvp via ../../iverilog/vvp-static-build/BUILD.md; regenerate bluesv.vvp with bsc (see SOURCES.md)"
fi

[ "$miss" -eq 0 ] || echo "fetch-resources: bluesv/core — some artifacts absent; rebuild per SOURCES.md (bsc host tool + vvp-static-build)" >&2
echo "fetch-resources: bluesv/core OK"
