//
// Generated by Bluespec Compiler, version 2026.01-54-ge8b70f8c (build e8b70f8c)
//
// On Sat May 30 04:30:07 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_inc                        O     1 const
// value                          O     8 reg
// RDY_value                      O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// EN_inc                         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCounter(CLK,
		 RST_N,

		 EN_inc,
		 RDY_inc,

		 value,
		 RDY_value);
  input  CLK;
  input  RST_N;

  // action method inc
  input  EN_inc;
  output RDY_inc;

  // value method value
  output [7 : 0] value;
  output RDY_value;

  // signals for module outputs
  wire [7 : 0] value;
  wire RDY_inc, RDY_value;

  // register cnt
  reg [7 : 0] cnt;
  wire [7 : 0] cnt$D_IN;
  wire cnt$EN;

  // action method inc
  assign RDY_inc = 1'd1 ;

  // value method value
  assign value = cnt ;
  assign RDY_value = 1'd1 ;

  // register cnt
  assign cnt$D_IN = cnt + 8'd1 ;
  assign cnt$EN = EN_inc ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        cnt <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (cnt$EN) cnt <= `BSV_ASSIGNMENT_DELAY cnt$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    cnt = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCounter

