//
// Generated by Bluespec Compiler, version 2026.01-54-ge8b70f8c (build e8b70f8c)
//
// On Sat May 30 04:30:07 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // register i
  reg [7 : 0] i;
  wire [7 : 0] i$D_IN;
  wire i$EN;

  // ports of submodule c
  wire [7 : 0] c$value;
  wire c$EN_inc;

  // remaining internal signals
  wire i_ULT_8___d2;

  // submodule c
  mkCounter c(.CLK(CLK),
	      .RST_N(RST_N),
	      .EN_inc(c$EN_inc),
	      .RDY_inc(),
	      .value(c$value),
	      .RDY_value());

  // register i
  assign i$D_IN = i + 8'd1 ;
  assign i$EN = i_ULT_8___d2 ;

  // submodule c
  assign c$EN_inc = i_ULT_8___d2 ;

  // remaining internal signals
  assign i_ULT_8___d2 = i < 8'd8 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        i <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (i$EN) i <= `BSV_ASSIGNMENT_DELAY i$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    i = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (!i_ULT_8___d2) $display("BLUESV_COUNT=%0d", c$value);
    if (RST_N != `BSV_RESET_VALUE)
      if (!i_ULT_8___d2) $display("BLUESV_SIM_OK");
    if (RST_N != `BSV_RESET_VALUE) if (!i_ULT_8___d2) $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkTb

