//
// Generated by Bluespec Compiler, version 2026.01-54-ge8b70f8c (build e8b70f8c)
//
// On Mon Jun 15 12:37:16 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // register c_cnt
  reg [7 : 0] c_cnt;
  wire [7 : 0] c_cnt$D_IN;
  wire c_cnt$EN;

  // register done
  reg done;
  wire done$D_IN, done$EN;

  // register i
  reg [7 : 0] i;
  wire [7 : 0] i$D_IN;
  wire i$EN;

  // remaining internal signals
  wire i_ULT_8___d4;

  // register c_cnt
  assign c_cnt$D_IN = c_cnt + 8'd1 ;
  assign c_cnt$EN = !done && i_ULT_8___d4 ;

  // register done
  assign done$D_IN = 1'd1 ;
  assign done$EN = !done && !i_ULT_8___d4 ;

  // register i
  assign i$D_IN = i + 8'd1 ;
  assign i$EN = !done && i_ULT_8___d4 ;

  // remaining internal signals
  assign i_ULT_8___d4 = i < 8'd8 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        c_cnt <= `BSV_ASSIGNMENT_DELAY 8'd0;
	done <= `BSV_ASSIGNMENT_DELAY 1'd0;
	i <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (c_cnt$EN) c_cnt <= `BSV_ASSIGNMENT_DELAY c_cnt$D_IN;
	if (done$EN) done <= `BSV_ASSIGNMENT_DELAY done$D_IN;
	if (i$EN) i <= `BSV_ASSIGNMENT_DELAY i$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    c_cnt = 8'hAA;
    done = 1'h0;
    i = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (!done && !i_ULT_8___d4) $display("BH_COUNT=%0d", c_cnt);
    if (RST_N != `BSV_RESET_VALUE)
      if (!done && !i_ULT_8___d4) $display("BH_SQUARE=%0d", 32'd81);
    if (RST_N != `BSV_RESET_VALUE)
      if (!done && !i_ULT_8___d4) $display("BH_PAIR=%0d", 16'd42);
    if (RST_N != `BSV_RESET_VALUE)
      if (!done && !i_ULT_8___d4) $display("BH_VECSUM=%0d", 8'd10);
    if (RST_N != `BSV_RESET_VALUE)
      if (!done && !i_ULT_8___d4) $display("BH_SIM_OK");
    if (RST_N != `BSV_RESET_VALUE) if (!done && !i_ULT_8___d4) $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkTb

